# app.yaml

# Nome da sua Aplicação (Use o nome que está no seu painel da DO)
name: whale-app 

# Serviços (Seu backend)
services:
  - name: backend-acessor # O nome exato do seu componente (backend-acessor)
    
    # 1. Buildpack do Node.js (Base)
    buildpack: nodejs
    
    # 2. Comando de Pré-Build CRÍTICO: 
    # Instala o FFmpeg e depois compila o TypeScript.
    # Esta linha é a mais importante para resolver o problema do áudio.
    build_command: |
      apt-get update -y && apt-get install -y ffmpeg && npm run build
      
    # 3. Comando de Execução (Start Command)
    run_command: npm run start
    
    # 4. Configuração de Porta
    # A DigitalOcean App Platform usa a porta 8080 para o Health Check
    http_port: 8080
    
    # 5. Configuração de Rede
    routes:
      - path: /
      
    # Variáveis de Ambiente (Deixadas de fora, mas lidas do painel da DO)
    # Certifique-se de que GOOGLE_REDIRECT_URI e GOOGLE_REG_REDIRECT_URI estão corretas no painel